//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SR", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoạt động.
        /// </summary>
        internal static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ: Xã Phước Thuận, Huyện Xuyên Mộc, Tỉnh Bà Rịa Vũng Tàu, Việt Nam.
        /// </summary>
        internal static string Address_Info {
            get {
                return ResourceManager.GetString("Address_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãng hàng không.
        /// </summary>
        internal static string Airline {
            get {
                return ResourceManager.GetString("Airline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đón tại sân bay.
        /// </summary>
        internal static string AirportPickup {
            get {
                return ResourceManager.GetString("AirportPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi đặt phòng.
        /// </summary>
        internal static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá sự cố.
        /// </summary>
        internal static string Breakdown_Price {
            get {
                return ResourceManager.GetString("Breakdown_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chủ thẻ.
        /// </summary>
        internal static string Card_Holder_Name {
            get {
                return ResourceManager.GetString("Card_Holder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thẻ.
        /// </summary>
        internal static string Card_Number {
            get {
                return ResourceManager.GetString("Card_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại thẻ.
        /// </summary>
        internal static string Card_Type {
            get {
                return ResourceManager.GetString("Card_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày vào.
        /// </summary>
        internal static string Checkin {
            get {
                return ResourceManager.GetString("Checkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày ra.
        /// </summary>
        internal static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trẻ em.
        /// </summary>
        internal static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt phòng bằng thẻ tín dụng.
        /// </summary>
        internal static string Credit_Card_For_Booking {
            get {
                return ResourceManager.GetString("Credit_Card_For_Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CVC.
        /// </summary>
        internal static string CVCNumber {
            get {
                return ResourceManager.GetString("CVCNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        internal static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm đến.
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết thúc.
        /// </summary>
        internal static string End_Date {
            get {
                return ResourceManager.GetString("End_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ đề nghị đón.
        /// </summary>
        internal static string EstimatedArrivalTime {
            get {
                return ResourceManager.GetString("EstimatedArrivalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hết hạn.
        /// </summary>
        internal static string Expiry_Date {
            get {
                return ResourceManager.GetString("Expiry_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phản hồi của khách hàng.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyến bay.
        /// </summary>
        internal static string FlightNo {
            get {
                return ResourceManager.GetString("FlightNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dõi theo chúng tôi.
        /// </summary>
        internal static string Follow_Us {
            get {
                return ResourceManager.GetString("Follow_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyên ngày.
        /// </summary>
        internal static string Full_Day {
            get {
                return ResourceManager.GetString("Full_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ.
        /// </summary>
        internal static string GuestFirstName {
            get {
                return ResourceManager.GetString("GuestFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string GuestLastName {
            get {
                return ResourceManager.GetString("GuestLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nửa ngày.
        /// </summary>
        internal static string Half_Day {
            get {
                return ResourceManager.GetString("Half_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu.
        /// </summary>
        internal static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại giường.
        /// </summary>
        internal static string KindOfBed {
            get {
                return ResourceManager.GetString("KindOfBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại cuộc họp.
        /// </summary>
        internal static string Kind_Of_Meeting {
            get {
                return ResourceManager.GetString("Kind_Of_Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng họp &amp; Sự kiện.
        /// </summary>
        internal static string Meeting_And_Event {
            get {
                return ResourceManager.GetString("Meeting_And_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin nhắn.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không hút thuốc.
        /// </summary>
        internal static string NonSmorking {
            get {
                return ResourceManager.GetString("NonSmorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng khách.
        /// </summary>
        internal static string NoOfGuest {
            get {
                return ResourceManager.GetString("NoOfGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng phòng.
        /// </summary>
        internal static string NoOfRoom {
            get {
                return ResourceManager.GetString("NoOfRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng khách.
        /// </summary>
        internal static string Number_Of_Guest {
            get {
                return ResourceManager.GetString("Number_Of_Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trọn gói.
        /// </summary>
        internal static string Package_Price {
            get {
                return ResourceManager.GetString("Package_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tác.
        /// </summary>
        internal static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt phòng nhanh.
        /// </summary>
        internal static string Quick_Reservation {
            get {
                return ResourceManager.GetString("Quick_Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà hàng &amp; Quán Bar.
        /// </summary>
        internal static string Restaurant_And_Bar {
            get {
                return ResourceManager.GetString("Restaurant_And_Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khuyến mãi nhà hàng.
        /// </summary>
        internal static string Restaurant_Deal {
            get {
                return ResourceManager.GetString("Restaurant_Deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng.
        /// </summary>
        internal static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng &amp; Giá phòng.
        /// </summary>
        internal static string Room_And_Price {
            get {
                return ResourceManager.GetString("Room_And_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá phòng khuyến mãi.
        /// </summary>
        internal static string Room_Deal {
            get {
                return ResourceManager.GetString("Room_Deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu đặc biệt.
        /// </summary>
        internal static string SpecialRequest {
            get {
                return ResourceManager.GetString("SpecialRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu.
        /// </summary>
        internal static string Start_Date {
            get {
                return ResourceManager.GetString("Start_Date", resourceCulture);
            }
        }
    }
}
